{
    'name': 'TAJ Navirec Fleet Integration',
    'version': '19.0.1.2.0',
    'summary': 'Sync Navirec vehicle positions and telematics into Odoo Fleet',
    'category': 'Human Resources/Fleet',
    'author': 'TAJ Trucking',
    'license': 'LGPL-3',
    'depends': ['fleet', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'views/fleet_vehicle_views.xml',
        'views/res_config_settings_views.xml',
        'views/report_subscription_views.xml',
        'views/navirec_sync_log_views.xml',
    ],
    'external_dependencies': {'python': ['requests']},
    'installable': True,
    'application': False,
    'auto_install': False,
}
